const LEVELS = {
  HIGH_BREACH: "HIGH_BREACH",
  LOW_BREACH: "LOW_BREACH",
  LOW_WARNING: "LOW_WARNING",
  HIGH_WARNING: "HIGH_WARNING",
  NORMAL: "NORMAL",
};
const MESSAGES = {
  en: {
    LOW_BREACH_TEMP: "Error: Temperature is Low",
    HIGH_BREACH_TEMP: "Error: Temperature is High",
    LOW_WARNING_TEMP: "Warning: Temperature approaching lower limit",
    HIGH_WARNING_TEMP: "Warning: Temperature approaching higher limit",
    NORMAL_TEMP: "Temperature in Range",
    LOW_BREACH_SOC: "Error: SOC is Low",
    HIGH_BREACH_SOC: "Error: SOC is High",
    LOW_WARNING_SOC: "Warning: SOC approaching lower limit",
    HIGH_WARNING_SOC: "Warning: SOC approaching higher limit",
    NORMAL_SOC: "SOC in Range",
    LOW_BREACH_CR: "Error: Charge rate is low",
    HIGH_BREACH_CR: "Error: Charge rate is high",
    LOW_WARNING_CR: "Warning: Charge rate approaching lower limit",
    HIGH_WARNING_CR: "Warning: Charge rate approaching higher limit",
    NORMAL_CR: "Charge Rate in Rage",
  },
  de: {
    LOW_BREACH_TEMP: "Error: Temperature is Low - GERMAN",
    HIGH_BREACH_TEMP: "Error: Temperature is High - GERMAN",
    LOW_WARNING_TEMP: "Warning: Temperature approaching lower limit - GERMAN",
    HIGH_WARNING_TEMP: "Warning: Temperature approaching higher limit - GERMAN",
    NORMAL_TEMP: "Temperature in Range - GERMAN",
    LOW_BREACH_SOC: "Error: SOC is Low - GERMAN",
    HIGH_BREACH_SOC: "Error: SOC is High - GERMAN",
    LOW_WARNING_SOC: "Warning: SOC approaching lower limit - GERMAN",
    HIGH_WARNING_SOC: "Warning: SOC approaching higher limit - GERMAN",
    NORMAL_SOC: "SOC in Range - GERMAN",
    LOW_BREACH_CR: "Error: Charge rate is low - GERMAN",
    HIGH_BREACH_CR: "Error: Charge rate is high - GERMAN",
    LOW_WARNING_CR: "Warning: Charge rate approaching lower limit - GERMAN",
    HIGH_WARNING_CR: "Warning: Charge rate approaching higher limit - GERMAN",
    NORMAL_CR: "Charge Rate in Rage - GERMAN",
  },
};
const BMS_CONFIG = {
  temperature: {
    min: 0,
    max: 45,
    tolerance: 5,
    LOW_BREACH: "LOW_BREACH_TEMP",
    HIGH_BREACH: "HIGH_BREACH_TEMP",
    LOW_WARNING: "LOW_WARNING_TEMP",
    HIGH_WARNING: "HIGH_WARNING_TEMP",
    NORMAL: "NORMAL_TEMP",
  },
  stateOfCharge: {
    min: 20,
    max: 80,
    tolerance: 5,
    LOW_BREACH: "LOW_BREACH_SOC",
    HIGH_BREACH: "HIGH_BREACH_SOC",
    LOW_WARNING: "LOW_WARNING_SOC",
    HIGH_WARNING: "HIGH_WARNING_SOC",
    NORMAL: "NORMAL_SOC",
  },
  chargeRate: {
    max: 0.8,
    tolerance: 5,
    LOW_BREACH: "LOW_BREACH_CR",
    HIGH_BREACH: "HIGH_BREACH_CR",
    LOW_WARNING: "LOW_WARNING_CR",
    HIGH_WARNING: "HIGH_WARNING_CR",
    NORMAL: "NORMAL_CR",
  },
};
module.exports = { BMS_CONFIG, MESSAGES, LEVELS };
